export const ARABIC_BOOK_TAGS = [
  { label: 'رواية', value: 'رواية' },
  { label: 'غير روائي', value: 'غير روائي' },
  { label: 'كلاسيكيات', value: 'كلاسيكيات' },
  { label: 'معاصر', value: 'معاصر' },
  { label: 'أدب', value: 'أدب' },
  { label: 'يافعين', value: 'يافعين' },
  { label: 'أطفال', value: 'أطفال' },
  { label: 'قصص مصورة', value: 'قصص مصورة' },
  { label: 'رواية مصورة', value: 'رواية مصورة' },
  { label: 'شعر', value: 'شعر' },
  { label: 'مسرح', value: 'مسرح' },
  { label: 'قصص قصيرة', value: 'قصص قصيرة' },
  { label: 'مختارات', value: 'مختارات' },

  { label: 'فانتازيا', value: 'فانتازيا' },
  { label: 'فانتازيا عالية', value: 'فانتازيا عالية' },
  { label: 'فانتازيا ملحمية', value: 'فانتازيا ملحمية' },
  { label: 'فانتازيا حضرية', value: 'فانتازيا حضرية' },
  { label: 'فانتازيا مظلمة', value: 'فانتازيا مظلمة' },
  { label: 'خيال علمي', value: 'خيال علمي' },
  { label: 'ديستوبيا', value: 'ديستوبيا' },
  { label: 'سايبربنك', value: 'سايبربنك' },
  { label: 'ما بعد الكارثة', value: 'ما بعد الكارثة' },
  { label: 'السفر عبر الزمن', value: 'السفر عبر الزمن' },
  { label: 'رومانس', value: 'رومانس' },
  { label: 'رومانس تاريخي', value: 'رومانس تاريخي' },
  { label: 'رومانس معاصر', value: 'رومانس معاصر' },
  { label: 'رومانس خارق', value: 'رومانس خارق' },
  { label: 'إثارة', value: 'إثارة' },
  { label: 'غموض', value: 'غموض' },
  { label: 'تحقيق', value: 'تحقيق' },
  { label: 'جريمة', value: 'جريمة' },
  { label: 'تشويق', value: 'تشويق' },
  { label: 'رعب', value: 'رعب' },
  { label: 'قوطي', value: 'قوطي' },
  { label: 'خارق للطبيعة', value: 'خارق للطبيعة' },
  { label: 'مغامرة', value: 'مغامرة' },
  { label: 'أكشن', value: 'أكشن' },
  { label: 'رواية تاريخية', value: 'رواية تاريخية' },
  { label: 'رواية حرب', value: 'رواية حرب' },
  { label: 'أساطير', value: 'أساطير' },
  { label: 'فولكلور', value: 'فولكلور' },
  { label: 'الواقعية السحرية', value: 'الواقعية السحرية' },
  { label: 'سخرية', value: 'سخرية' },
  { label: 'كوميديا', value: 'كوميديا' },

  { label: 'سيرة ذاتية', value: 'سيرة ذاتية' },
  { label: 'مذكرات', value: 'مذكرات' },
  { label: 'تاريخ', value: 'تاريخ' },
  { label: 'سياسة', value: 'سياسة' },
  { label: 'فلسفة', value: 'فلسفة' },
  { label: 'علم النفس', value: 'علم النفس' },
  { label: 'علم اجتماع', value: 'علم اجتماع' },
  { label: 'تنمية ذاتية', value: 'تنمية ذاتية' },
  { label: 'تحفيز', value: 'تحفيز' },
  { label: 'إنتاجية', value: 'إنتاجية' },
  { label: 'أعمال', value: 'أعمال' },
  { label: 'اقتصاد', value: 'اقتصاد' },
  { label: 'مالية', value: 'مالية' },
  { label: 'استثمار', value: 'استثمار' },
  { label: 'ريادة أعمال', value: 'ريادة أعمال' },
  { label: 'قيادة', value: 'قيادة' },
  { label: 'تسويق', value: 'تسويق' },
  { label: 'مبيعات', value: 'مبيعات' },
  { label: 'إدارة', value: 'إدارة' },
  { label: 'تعليم', value: 'تعليم' },
  { label: 'علوم', value: 'علوم' },
  { label: 'تقنية', value: 'تقنية' },
  { label: 'ذكاء اصطناعي', value: 'ذكاء اصطناعي' },
  { label: 'علوم الحاسوب', value: 'علوم الحاسوب' },
  { label: 'برمجة', value: 'برمجة' },
  { label: 'رياضيات', value: 'رياضيات' },
  { label: 'فيزياء', value: 'فيزياء' },
  { label: 'أحياء', value: 'أحياء' },
  { label: 'كيمياء', value: 'كيمياء' },
  { label: 'صحة', value: 'صحة' },
  { label: 'تغذية', value: 'تغذية' },
  { label: 'لياقة', value: 'لياقة' },
  { label: 'طب', value: 'طب' },
  { label: 'روحانيات', value: 'روحانيات' },
  { label: 'دين', value: 'دين' },
  { label: 'إسلاميات', value: 'إسلاميات' },
  { label: 'مسيحية', value: 'مسيحية' },
  { label: 'يهودية', value: 'يهودية' },
  { label: 'سفر', value: 'سفر' },
  { label: 'طبخ', value: 'طبخ' },
  { label: 'فنون', value: 'فنون' },
  { label: 'تصوير', value: 'تصوير' },
  { label: 'تصميم', value: 'تصميم' },
  { label: 'عمارة', value: 'عمارة' },
  { label: 'اصنعه بنفسك', value: 'اصنعه بنفسك' },
  { label: 'تحسين المنزل', value: 'تحسين المنزل' },
  { label: 'بيئة', value: 'بيئة' },
  { label: 'طبيعة', value: 'طبيعة' },
  { label: 'جريمة حقيقية', value: 'جريمة حقيقية' },

  { label: 'كتاب مدرسي', value: 'كتاب مدرسي' },
  { label: 'بحث', value: 'بحث' },
  { label: 'أكاديمي', value: 'أكاديمي' },
  { label: 'جامعة', value: 'جامعة' },
  { label: 'مدرسة', value: 'مدرسة' },
  { label: 'دليل دراسة', value: 'دليل دراسة' },
  { label: 'تحضير امتحان', value: 'تحضير امتحان' },
  { label: 'مرجع', value: 'مرجع' },
  { label: 'قاموس', value: 'قاموس' },
  { label: 'موسوعة', value: 'موسوعة' },
  { label: 'مجلة علمية', value: 'مجلة علمية' },
  { label: 'ورقة علمية', value: 'ورقة علمية' },
  { label: 'هندسة', value: 'هندسة' },
  { label: 'قانون', value: 'قانون' },
  { label: 'إحصاء', value: 'إحصاء' },
  { label: 'علوم البيانات', value: 'علوم البيانات' },
  { label: 'تعلم الآلة', value: 'تعلم الآلة' },
  { label: 'الحوسبة السحابية', value: 'الحوسبة السحابية' },
  { label: 'تطوير ويب', value: 'تطوير ويب' },
  { label: 'تطوير تطبيقات', value: 'تطوير تطبيقات' },

  { label: 'عربي', value: 'عربي' },
  { label: 'إنجليزي', value: 'إنجليزي' },
  { label: 'فرنسي', value: 'فرنسي' },
  { label: 'ألماني', value: 'ألماني' },
  { label: 'إسباني', value: 'إسباني' },
  { label: 'ياباني', value: 'ياباني' },
  { label: 'صيني', value: 'صيني' },
  { label: 'هندي', value: 'هندي' },
  { label: 'الشرق الأوسط', value: 'الشرق الأوسط' },
  { label: 'أمريكي', value: 'أمريكي' },
  { label: 'أوروبي', value: 'أوروبي' },
  { label: 'آسيوي', value: 'آسيوي' },
  { label: 'أفريقي', value: 'أفريقي' },
  { label: 'الأردن', value: 'الأردن' },

  { label: 'متوسطون', value: 'متوسطون' },
  { label: 'كبار', value: 'كبار' },

  { label: 'الأكثر مبيعًا', value: 'الأكثر مبيعًا' },
  { label: 'حائز على جوائز', value: 'حائز على جوائز' },
  { label: 'إصدار جديد', value: 'إصدار جديد' },
  { label: 'أدب كلاسيكي', value: 'أدب كلاسيكي' },
  { label: 'قراءة طويلة', value: 'قراءة طويلة' },
  { label: 'قراءة قصيرة', value: 'قراءة قصيرة' },
  { label: 'سلسلة', value: 'سلسلة' },
  { label: 'مستقل', value: 'مستقل' },
  { label: 'مجاني', value: 'مجاني' },
  { label: 'مدفوع', value: 'مدفوع' },
  { label: 'PDF', value: 'PDF' },
  { label: 'EPUB', value: 'EPUB' },
  { label: 'كتاب صوتي', value: 'كتاب صوتي' },

  { label: 'حب', value: 'حب' },
  { label: 'صداقة', value: 'صداقة' },
  { label: 'عائلة', value: 'عائلة' },
  { label: 'شجاعة', value: 'شجاعة' },
  { label: 'نمو', value: 'نمو' },
  { label: 'بقاء', value: 'بقاء' },
  { label: 'عدالة', value: 'عدالة' },
  { label: 'انتقام', value: 'انتقام' },
  { label: 'أخلاق', value: 'أخلاق' },
  { label: 'أمل', value: 'أمل' },
  { label: 'حرب', value: 'حرب' },
  { label: 'سلام', value: 'سلام' },
  { label: 'علم', value: 'علم' },
  { label: 'تاريخ بديل', value: 'تاريخ بديل' },
  { label: 'ظلام', value: 'ظلام' },
  { label: 'خفيف ولطيف', value: 'خفيف ولطيف' },
  { label: 'تأمل', value: 'تأمل' },
  { label: 'يقظة ذهنية', value: 'يقظة ذهنية' },
  { label: 'ثروة', value: 'ثروة' },
  { label: 'سعادة', value: 'سعادة' },
  { label: 'تبسيط الحياة', value: 'تبسيط الحياة' },
  { label: 'روايات مصورة يابانية', value: 'روايات مصورة يابانية' },
  { label: 'أنمي', value: 'أنمي' },
];

export const READING_STATUSES = [
  { value: 'not_started', label: 'Not Started' },
  { value: 'reading', label: 'Reading' },
  { value: 'finished', label: 'Finished' },
  { value: 'abandoned', label: 'Abandoned' },
];
