import { IExerciseDetails } from '_types/types';

export const workoutDatabase: IExerciseDetails[] = [
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'machine chest press',
    equipment: 'machine',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'smith machine bench press',
    equipment: 'machine',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'barbell bench press - medium grip',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'barbell bench press - wide-grip',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'dumbbells bench press',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'hammer grip dumbbells bench press',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'single-arm dumbbells bench press',
    equipment: 'dumbbells',
  },

  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'cable chest press',
    equipment: 'cable',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'standing cable chest press',
    equipment: 'cable',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'single-arm standing cable chest press',
    equipment: 'cable',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'alternating floor press',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'push-up',
    equipment: 'bodyweight',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'push-up wide hand positions',
    equipment: 'bodyweight',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'push-up close hand positions',
    equipment: 'bodyweight',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'push-ups with feet elevated',
    equipment: 'bodyweight',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'single-arm push-up',
    equipment: 'none',
  },

  {
    muscleGroup: 'chest',
    muscleSubgroup: 'upper chest (clavicular pectoralis)',
    exercise: 'smith machine incline bench press',
    equipment: 'machine',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'upper chest (clavicular pectoralis)',
    exercise: 'incline barbell bench press',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'upper chest (clavicular pectoralis)',
    exercise: 'incline dumbbell press',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'upper chest (clavicular pectoralis)',
    exercise: 'hammer grip incline dumbbells bench press',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'upper chest (clavicular pectoralis)',
    exercise: 'incline cable chest press',
    equipment: 'cable',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'upper chest (clavicular pectoralis)',
    exercise: 'incline push-up',
    equipment: 'none',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'upper chest (clavicular pectoralis)',
    exercise: 'incline push-up wide',
    equipment: 'none',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'upper chest (clavicular pectoralis)',
    exercise: 'incline push-up reverse grip',
    equipment: 'none',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'lower chest (costal pectoralis)',
    exercise: 'smith machine decline press',
    equipment: 'machine',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'lower chest (costal pectoralis)',
    exercise: 'decline barbell bench press',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'lower chest (costal pectoralis)',
    exercise: 'decline dumbbell bench press',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'lower chest (costal pectoralis)',
    exercise: 'dips - chest version',
    equipment: 'machine',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'lower chest (costal pectoralis)',
    exercise: 'decline push-up',
    equipment: 'none',
  },

  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'pec deck',
    equipment: 'machine',
  },

  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'dumbbell flyes',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'one-arm flat bench dumbbell fly',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'flat bench cable flyes',
    equipment: 'cable',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'upper chest (clavicular pectoralis)',
    exercise: 'incline dumbbell flyes',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'upper chest (clavicular pectoralis)',
    exercise: 'incline cable flyes',
    equipment: 'cable',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'lower chest (costal pectoralis)',
    exercise: 'decline dumbbell flyes',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'lower chest (costal pectoralis)',
    exercise: 'cable crossover',
    equipment: 'cable',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'lower chest (costal pectoralis)',
    exercise: 'crossover - with bands',
    equipment: 'bands',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'upper chest (clavicular pectoralis)',
    exercise: 'low cable crossover',
    equipment: 'cable',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'lower chest (costal pectoralis)',
    exercise: 'single-arm cable crossover high-pulley',
    equipment: 'cable',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'middle chest (sternal pectoralis)',
    exercise: 'single-arm cable crossover mid-pulley',
    equipment: 'cable',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'upper chest (clavicular pectoralis)',
    exercise: 'single-arm cable crossover low-pulley',
    equipment: 'cable',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'chest',
    exercise: 'front raise and pullover',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'chest',
    exercise: 'bent-arm dumbbell pullover',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'chest',
    exercise: 'straight-arm dumbbell pullover',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'chest',
    muscleSubgroup: 'chest',
    exercise: 'around the worlds',
    equipment: 'dumbbells',
  },

  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'machine shoulder press',
    equipment: 'machine',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'smith machine overhead shoulder press',
    equipment: 'machine',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'standing barbell military press',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'seated barbell military press',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'arnold dumbbell press',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'standing dumbbell shoulder press',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'seated dumbbell shoulder press',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'single-arm dumbbell press',
    equipment: 'dumbbells',
  },

  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'standing alternating dumbbell press',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'standing palm-in one-arm dumbbell press',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'standing palms-in dumbbell press',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'cable shoulder press',
    equipment: 'cable',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'seated cable shoulder press',
    equipment: 'cable',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'shoulder press - with bands',
    equipment: 'bands',
  },

  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'barbell shoulder front raise',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'barbell incline shoulder front raise',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'standing dumbbell shoulder front raise',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'seated dumbbells shoulder front raise',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'alternating dumbbells shoulder front raise',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'dumbbell incline shoulder front raise',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'standing low-pulley shoulder front raise',
    equipment: 'cable',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'incline dumbbell shoulder front raise',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'front plate shoulder front raise',
    equipment: 'plates',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'front deltoid (anterior deltoid)',
    exercise: 'side laterals to front raise',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'side deltoid (lateral deltoid)',
    exercise: 'standing side lateral raise',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'side deltoid (lateral deltoid)',
    exercise: 'seated side lateral raise',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'side deltoid (lateral deltoid)',
    exercise: 'lying one-arm lateral raise',
    equipment: 'none',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'side deltoid (lateral deltoid)',
    exercise: 'single-arm incline lateral raise',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'side deltoid (lateral deltoid)',
    exercise: 'single-arm side laterals raise',
    equipment: 'cable',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'side deltoid (lateral deltoid)',
    exercise: 'cable seated lateral raise',
    equipment: 'cable',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'side deltoid (lateral deltoid)',
    exercise: 'lateral raise - with bands',
    equipment: 'bands',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'side deltoid (lateral deltoid)',
    exercise: 'upright cable row',
    equipment: 'cable',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'side deltoid (lateral deltoid)',
    exercise: 'upright barbell row',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'side deltoid (lateral deltoid)',
    exercise: 'dumbbell single-arm upright row',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'rear deltoid (posterior deltoid)',
    exercise: 'face pull',
    equipment: 'cable',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'rear deltoid (posterior deltoid)',
    exercise: 'cable rear delt fly - high-pulley',
    equipment: 'cable',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'rear deltoid (posterior deltoid)',
    exercise: 'cable rear delt fly - mid-pulley',
    equipment: 'cable',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'rear deltoid (posterior deltoid)',
    exercise: 'cable rear delt fly - low-pulley',
    equipment: 'cable',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'rear deltoid (posterior deltoid)',
    exercise: 'bent over dumbbells rear delt',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'rear deltoid (posterior deltoid)',
    exercise: 'single-arm bent over cable rear delt',
    equipment: 'cable',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'rear deltoid (posterior deltoid)',
    exercise: 'dumbbell lying one-arm rear lateral raise',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'rear deltoid (posterior deltoid)',
    exercise: 'reverse machine flyes',
    equipment: 'machine',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'rear deltoid (posterior deltoid)',
    exercise: 'seated bent-over rear delt raise',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'rear deltoid (posterior deltoid)',
    exercise: 'back flyes - with bands',
    equipment: 'bands',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'rear deltoid (posterior deltoid)',
    exercise: 'band pull apart',
    equipment: 'bands',
  },
  {
    muscleGroup: 'shoulders',
    muscleSubgroup: 'rear deltoid (posterior deltoid)',
    exercise: 'barbell rear delt row',
    equipment: 'barbell',
  },

  {
    muscleGroup: 'back',
    muscleSubgroup: 'lats (latissimus dorsi)',
    exercise: 'pull-ups',
    equipment: 'bodyweight',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'lats (latissimus dorsi)',
    exercise: 'v-bar pullup',
    equipment: 'bodyweight',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'lats (latissimus dorsi)',
    exercise: 'chin-up',
    equipment: 'bodyweight',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'lats (latissimus dorsi)',
    exercise: 'wide-grip lat pulldown',
    equipment: 'cable',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'lats (latissimus dorsi)',
    exercise: 'close-grip lat pulldown',
    equipment: 'cable',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'lats (latissimus dorsi)',
    exercise: 'underhand cable pulldowns',
    equipment: 'cable',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'lats (latissimus dorsi)',
    exercise: 'v-bar pulldown',
    equipment: 'cable',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'lats (latissimus dorsi)',
    exercise: 'single-arm lat pulldown',
    equipment: 'cable',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'lats (latissimus dorsi)',
    exercise: 'single-arm shotgun row',
    equipment: 'cable',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'lats (latissimus dorsi)',
    exercise: 'straight-arm pulldown bar-attachment',
    equipment: 'cable',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'lats (latissimus dorsi)',
    exercise: 'straight-arm pulldown rop-attachment',
    equipment: 'cable',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'lats (latissimus dorsi)',
    exercise: 'cable incline pushdown',
    equipment: 'cable',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'lats (latissimus dorsi)',
    exercise: 'bent-arm barbell pullover',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'middle back (lats, rhomboids & traps)',
    exercise: 'seated cable rows - bar attachment',
    equipment: 'cable',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'middle back (lats, rhomboids & traps)',
    exercise: 'seated cable rows - v-bar attachment',
    equipment: 'cable',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'middle back (lats, rhomboids & traps)',
    exercise: 'seated single-arm cable pulley rows',
    equipment: 'cable',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'middle back (lats, rhomboids & traps)',
    exercise: 'bent over barbell row',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'middle back (lats, rhomboids & traps)',
    exercise: 'bent over one-arm long bar row',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'middle back (lats, rhomboids & traps)',
    exercise: 'bent over two-arm long bar row',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'middle back (lats, rhomboids & traps)',
    exercise: 'bent over two-dumbbell row',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'middle back (lats, rhomboids & traps)',
    exercise: 'bent over two-dumbbell row with palms in',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'middle back (lats, rhomboids & traps)',
    exercise: 'middle back shrug',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'middle back (lats, rhomboids & traps)',
    exercise: 'single-arm dumbbell row',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'middle back (lats, rhomboids & traps)',
    exercise: 'single-arm long bar row',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'middle back (lats, rhomboids & traps)',
    exercise: 'reverse grip bent-over rows',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'middle back (lats, rhomboids & traps)',
    exercise: 'smith machine bent over row',
    equipment: 'machine',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'middle back (lats, rhomboids & traps)',
    exercise: 'lying t-bar row',
    equipment: 'machine',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'middle back (lats, rhomboids & traps)',
    exercise: 't-bar row with handle',
    equipment: 'machine',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'lower back (erector spinae)',
    exercise: 'deadlift',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'lower back (erector spinae)',
    exercise: 'deadlift with bands',
    equipment: 'bands',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'lower back (erector spinae)',
    exercise: 'back extensions',
    equipment: 'machine',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'lower back (erector spinae)',
    exercise: 'seated good mornings',
    equipment: 'none',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'lower back (erector spinae)',
    exercise: 'stiff leg barbell good morning',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'upper back (trapezius & rhomboids)',
    exercise: 'barbell shrug',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'upper back (trapezius & rhomboids)',
    exercise: 'barbell shrug behind the back',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'upper back (trapezius & rhomboids)',
    exercise: 'cable shrugs',
    equipment: 'cable',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'upper back (trapezius & rhomboids)',
    exercise: 'calf-machine shoulder shrug',
    equipment: 'machine',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'upper back (trapezius & rhomboids)',
    exercise: 'dumbbell shrug',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'upper back (trapezius & rhomboids)',
    exercise: 'leverage shrug',
    equipment: 'machine',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'upper back (trapezius & rhomboids)',
    exercise: 'smith machine behind the back shrug',
    equipment: 'machine',
  },
  {
    muscleGroup: 'back',
    muscleSubgroup: 'upper back (trapezius & rhomboids)',
    exercise: 'smith machine shrug',
    equipment: 'machine',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps',
    exercise: 'machine bicep curl',
    equipment: 'machine',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps',
    exercise: 'barbell curl',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps',
    exercise: 'ez-bar curl',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps brachii long head (outer biceps)',
    exercise: 'barbell drag curl',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps brachii short head (inner biceps)',
    exercise: 'dumbbell alternate bicep curl',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps brachii short head (inner biceps)',
    exercise: 'dumbbell bicep curl',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps brachii short head (inner biceps)',
    exercise: 'seated dumbbell curl',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps',
    exercise: 'standing biceps cable curl - bar attachment',
    equipment: 'cable',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps brachii',
    exercise: 'standing single-arm cable curl',
    equipment: 'cable',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps brachii short head (inner biceps)',
    exercise: 'single-arm concentration curls',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps brachii',
    exercise: 'machine preacher curls',
    equipment: 'machine',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps brachii',
    exercise: 'barbell preacher curl',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps brachii',
    exercise: 'dumbbells preacher curl',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps brachii',
    exercise: 'single-arm dumbbell preacher curl',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps brachii',
    exercise: 'cables preacher curl - bar attachment',
    equipment: 'cable',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps brachii long head (outer biceps)',
    exercise: 'incline cables curls - rope attachment',
    equipment: 'cable',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps brachii long head (outer biceps)',
    exercise: 'incline dumbbell curl',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps brachii long head (outer biceps)',
    exercise: 'alternate incline dumbbell curl',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps brachii long head (outer biceps)',
    exercise: 'flexor incline dumbbell curls',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps brachii',
    exercise: 'standing one-arm dumbbell curl over incline bench',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'brachialis (underneath biceps)',
    exercise: 'incline hammer curls',
    equipment: 'cable',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'brachialis (underneath biceps)',
    exercise: 'preacher hammer dumbbell curl',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'brachialis (underneath biceps)',
    exercise: 'alternate hammer curl',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'brachialis (underneath biceps)',
    exercise: 'dumbbells hammer curl',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'brachialis (underneath biceps)',
    exercise: 'cross body hammer curl',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'brachialis (underneath biceps)',
    exercise: 'cable hammer curls - rope attachment',
    equipment: 'cable',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'forearm brachioradialis',
    exercise: 'reverse barbell curl',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'forearm brachioradialis',
    exercise: 'reverse barbell preacher curls',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'forearm brachioradialis',
    exercise: 'standing dumbbell reverse curl',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'brachialis (underneath biceps)',
    exercise: 'reverse plate curls',
    equipment: 'plates',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'forearm brachioradialis',
    exercise: 'reverse cable curl - bar attachment',
    equipment: 'cable',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps brachii short head (inner biceps)',
    exercise: 'zottman curl',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'biceps',
    muscleSubgroup: 'biceps brachii long head (outer biceps)',
    exercise: 'zottman preacher curl',
    equipment: 'dumbbells',
  },
  // Triceps Brachii
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps brachii',
    exercise: 'body tricep press',
    equipment: 'bodyweight',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps brachii',
    exercise: 'dips - triceps version',
    equipment: 'machine',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps brachii',
    exercise: 'reverse grip triceps pushdown',
    equipment: 'none',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps brachii',
    exercise: 'reverse triceps bench press',
    equipment: 'none',
  },

  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps brachii',
    exercise: 'seated bent-over one-arm dumbbell triceps extension',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps brachii',
    exercise: 'seated bent-over two-arm dumbbell triceps extension',
    equipment: 'dumbbells',
  },

  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps brachii',
    exercise: 'weighted bench dip',
    equipment: 'machine',
  },

  // Long Head (Inner Triceps)
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'long head (inner triceps)',
    exercise: 'cable incline triceps extension',
    equipment: 'cable',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'long head (inner triceps)',
    exercise: 'cable lying triceps extension',
    equipment: 'cable',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'long head (inner triceps)',
    exercise: 'cable one arm tricep extension',
    equipment: 'cable',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'long head (inner triceps)',
    exercise: 'cable rope overhead triceps extension',
    equipment: 'cable',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'long head (inner triceps)',
    exercise: 'decline dumbbell triceps extension',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'long head (inner triceps)',
    exercise: 'decline ez-bar triceps extension',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'long head (inner triceps)',
    exercise: 'dumbbell single-arm triceps extension',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'long head (inner triceps)',
    exercise: 'dumbbell tricep extension - pronated grip',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'long head (inner triceps)',
    exercise: 'ez-bar skullcrusher',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'long head (inner triceps)',
    exercise: 'incline barbell triceps extension',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'long head (inner triceps)',
    exercise: 'low cable triceps extension',
    equipment: 'cable',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'long head (inner triceps)',
    exercise: 'lying dumbbell tricep extension',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'long head (inner triceps)',
    exercise: 'lying triceps press',
    equipment: 'none',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'long head (inner triceps)',
    exercise: 'machine triceps extension',
    equipment: 'machine',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'long head (inner triceps)',
    exercise: 'one arm pronated dumbbell triceps extension',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'long head (inner triceps)',
    exercise: 'one arm supinated dumbbell triceps extension',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'long head (inner triceps)',
    exercise: 'overhead triceps',
    equipment: 'none',
  },

  // Lateral Head (Outer Triceps)
  // (Note: No specific exercises were listed for this subgroup in your previous data)

  // Medial Head (Middle Triceps)
  // (Note: No specific exercises were listed for this subgroup in your previous data)

  // General Triceps
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps',
    exercise: 'band skull crusher',
    equipment: 'bands',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps',
    exercise: 'speed band overhead triceps',
    equipment: 'bands',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps',
    exercise: 'speed band pushdown',
    equipment: 'bands',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps',
    exercise: 'standing bent-over one-arm dumbbell triceps extension',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps',
    exercise: 'standing bent-over two-arm dumbbell triceps extension',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps',
    exercise: 'standing dumbbell triceps extension',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps',
    exercise: 'standing low-pulley one-arm triceps extension',
    equipment: 'cable',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps',
    exercise: 'standing one-arm dumbbell triceps extension',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps',
    exercise: 'standing overhead barbell triceps extension',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps',
    exercise: 'standing towel triceps extension',
    equipment: 'none',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps',
    exercise: 'supine chest throw',
    equipment: 'none',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps',
    exercise: 'tate press',
    equipment: 'none',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps',
    exercise: 'tricep dumbbell kickback',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps',
    exercise: 'tricep side stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps',
    exercise: 'triceps overhead extension with rope',
    equipment: 'rope',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps',
    exercise: 'triceps pushdown - bar attachment',
    equipment: 'cable',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps',
    exercise: 'triceps pushdown - rope attachment',
    equipment: 'cable',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps',
    exercise: 'triceps pushdown - v-bar attachment',
    equipment: 'cable',
  },
  {
    muscleGroup: 'triceps',
    muscleSubgroup: 'triceps',
    exercise: 'triceps stretch',
    equipment: 'none',
  },
  // Forearm Flexors
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'bottoms-up clean from the hang position',
    equipment: 'none',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'cable wrist curl',
    equipment: 'cable',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: "farmer's walk",
    equipment: 'none',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'finger curls',
    equipment: 'none',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'kneeling forearm stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'palms-down dumbbell wrist curl over a bench',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'palms-down wrist curl over a bench',
    equipment: 'none',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'palms-up barbell wrist curl over a bench',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'palms-up dumbbell wrist curl over a bench',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'plate pinch',
    equipment: 'none',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'rickshaw carry',
    equipment: 'none',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'seated dumbbell palms-down wrist curl',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'seated dumbbell palms-up wrist curl',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'seated one-arm dumbbell palms-down wrist curl',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'seated one-arm dumbbell palms-up wrist curl',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'seated palm-up barbell wrist curl',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'seated palms-down barbell wrist curl',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'seated two-arm palms-up low-pulley wrist curl',
    equipment: 'cable',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'standing olympic plate hand squeeze',
    equipment: 'none',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'standing palms-up barbell behind the back wrist curl',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'wrist circles',
    equipment: 'none',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'wrist roller',
    equipment: 'none',
  },
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm flexors',
    exercise: 'wrist rotations with straight bar',
    equipment: 'none',
  },

  // Forearm Pronators
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm pronators',
    exercise: 'dumbbell lying pronation',
    equipment: 'dumbbells',
  },

  // Forearm Supinators
  {
    muscleGroup: 'forearms',
    muscleSubgroup: 'forearm supinators',
    exercise: 'dumbbell lying supination',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'all fours quad stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'alternate leg diagonal bound',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'all fours quad stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'alternate leg diagonal bound',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'backward drag',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'barbell full squat',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'barbell hack squat',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'barbell lunge',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'barbell side split squat',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'barbell squat',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'barbell squat to a bench',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'barbell step ups',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'barbell walking lunge',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'bear crawl sled drags',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'bench jump',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'bench sprint',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'bicycling',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'bodyweight squat',
    equipment: 'bodyweight',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'bodyweight walking lunge',
    equipment: 'bodyweight',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'box squat',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'box squat with bands',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'box squat with chains',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'cable deadlifts',
    equipment: 'cable',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'cable hip adduction',
    equipment: 'cable',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'car deadlift',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'chair squat',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'clean from blocks',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'clean pull',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: "conan's wheel",
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'depth jump leap',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'double leg butt kick',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'dumbbell lunges',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'dumbbell rear lunge',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'dumbbell seated box jump',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'dumbbell squat',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'dumbbell squat to a bench',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'dumbbell step ups',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'elevated back lunge',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'elliptical trainer',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'fast skipping',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'frankenstein squat',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'freehand jump squat',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'frog hops',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'front barbell squat',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'front barbell squat to a bench',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'front cone hops (or hurdle hops)',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'front squat (clean grip)',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'front squats with two kettlebells',
    equipment: 'kettlebell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'goblet squat',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'hack squat',
    equipment: 'machine',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'hang clean',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'hang clean - below the knees',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'heaving snatch balance',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'hip flexion with band',
    equipment: 'bands',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'intermediate hip flexor and quad stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'iron crosses (stretch)',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'jefferson squats',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'jerk dip squat',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'jogging-treadmill',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'kettlebell pistol squat',
    equipment: 'kettlebell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'kneeling hip flexor',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'leg extensions',
    equipment: 'machine',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'leg press',
    equipment: 'machine',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'leverage deadlift',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'linear depth jump',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'looking at ceiling',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'lunge sprint',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'lying machine squat',
    equipment: 'machine',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'lying prone quadriceps (front thighs)',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'mountain climbers',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'narrow stance hack squats',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'narrow stance leg press',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'narrow stance squats',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'olympic squat',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'on your side quad stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'on-your-back quad stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'one half locust',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'one leg barbell squat',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'one-arm overhead kettlebell squats',
    equipment: 'kettlebell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'one-arm side deadlift',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'overhead squat',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'plie dumbbell squat',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'power jerk',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'power snatch from blocks',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'quad stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'quadriceps (front thighs)-smr',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'quick leap',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'rear leg raises',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'recumbent bike',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'reverse band box squat',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'reverse band power squat',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'rickshaw deadlift',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'rocket jump',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'rope jumping',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'sandbag load',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'scissors jump',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'side hop-sprint',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'side standing long jump',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'side to side box shuffle',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'single leg butt kick',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'single leg push-off',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'single-cone sprint drill',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'single-leg high box squat',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'single-leg hop progression',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'single-leg lateral hop',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'single-leg leg extension',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'single-leg stride jump',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'sit squats',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'skating',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'sled drag - harness',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'sled push',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'smith machine leg press',
    equipment: 'machine',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'smith machine pistol squat',
    equipment: 'machine',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'smith machine squat',
    equipment: 'machine',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'smith single-leg split squat',
    equipment: 'machine',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'snatch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'snatch balance',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'snatch from blocks',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'speed box squat',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'speed squats',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'split clean',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'split jerk',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'split jump',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'split squat with dumbbells',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'squat jerk',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'squat with bands',
    equipment: 'bands',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'squat with chains',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'squat with plate movers',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'squats - with bands',
    equipment: 'bands',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'stairmaster',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'standing elevated quad stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'standing hip flexors',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'standing long jump',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'star jump',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'step mill',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'stride jump crossover',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'suspended split squat',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'tire flip',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'trail running/walking',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'trap bar deadlift',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'weighted jump squat',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'weighted sissy squat',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'weighted squat',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'wide stance barbell squat',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'yoke walk',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'quadriceps (front thighs)',
    exercise: 'zercher squats',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'alternating hang clean',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'ball leg curl',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'band good morning',
    equipment: 'bands',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'band good morning (pull through)',
    equipment: 'bands',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'box jump (multiple response)',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'box skip',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'chair leg extended stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'clean',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'clean deadlift',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'double kettlebell alternating hang clean',
    equipment: 'kettlebell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'dumbbell clean',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'floor glute-ham raise',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'front box jump',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'front leg raises',
    equipment: 'machine',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'glute ham raise',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'good morning',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'good morning off pins',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'hamstring stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'hamstring-smr',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'hang snatch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'hang snatch - below knees',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'hanging bar good morning',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'hurdle hops',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'intermediate groin stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'kettlebell dead clean',
    equipment: 'kettlebell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'kettlebell hang clean',
    equipment: 'kettlebell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'kettlebell one-legged deadlift',
    equipment: 'kettlebell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'knee tuck jump',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'leg-up hamstring stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'linear 3-part start technique',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'linear acceleration wall drill',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'lunge pass through',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'lying hamstring',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'lying leg curls',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'moving claw series',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'muscle snatch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'natural glute ham raise',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'one-arm kettlebell clean',
    equipment: 'kettlebell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'one-arm kettlebell swings',
    equipment: 'kettlebell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'one-arm open palm kettlebell clean',
    equipment: 'kettlebell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'open palm kettlebell clean',
    equipment: 'kettlebell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'platform hamstring slides',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'power clean',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'power clean from blocks',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'power snatch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'power stairs',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'prone manual hamstring',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'prowler sprint',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'reverse band sumo deadlift',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'reverse hyperextension',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'romanian deadlift',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'romanian deadlift from deficit',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: "runner's stretch",
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'seated band hamstring curl',
    equipment: 'bands',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'seated floor hamstring stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'seated hamstring',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'seated hamstring and calf stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'seated leg curl',
    equipment: 'machine',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'smith machine hang power clean',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'smith machine stiff-legged deadlift',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'snatch deadlift',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'snatch pull',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'split snatch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'split squats',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'standing hamstring and calf stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'standing leg curl',
    equipment: 'machine',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'standing toe touches',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'stiff-legged barbell deadlift',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'stiff-legged dumbbell deadlift',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'sumo deadlift',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'sumo deadlift with bands',
    equipment: 'bands',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'sumo deadlift with chains',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'the straddle',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'upper back-leg grab',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'vertical swing',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: 'wide stance stiff legs',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'hamstrings (back thighs)',
    exercise: "world's greatest stretch",
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'ankle circles',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'anterior tibialis-smr',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'ankle circles',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'anterior tibialis-smr',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'balance board',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'barbell seated calf raise',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'calf press',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'calf press on the leg press machine',
    equipment: 'machine',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'calf raise on a dumbbell',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'calf raises - with bands',
    equipment: 'bands',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'calf stretch elbows against wall',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'calf stretch hands against wall',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'calves-smr',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'donkey calf raises',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'dumbbell seated one-leg calf raise',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'foot-smr',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'knee circles',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'peroneals stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'peroneals-smr',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'posterior tibialis stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'rocking standing calf raise',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'seated calf raise',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'seated calf stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'smith machine calf raise',
    equipment: 'machine',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'smith machine reverse calf raises',
    equipment: 'machine',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'standing barbell calf raise',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'standing calf raises',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'standing dumbbell calf raise',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'standing gastrocnemius calf stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'calves',
    exercise: 'standing soleus and achilles stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'ankle on the knee',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'ankle on the knee',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'barbell glute bridge',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'barbell hip thrust',
    equipment: 'barbell',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'butt lift (bridge)',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'downward facing balance',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'flutter kicks',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'glute kickback',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'hip extension with bands',
    equipment: 'bands',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'hip lift with band',
    equipment: 'bands',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'knee across the body',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'kneeling jump squat',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'kneeling squat',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'leg lift',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'lying glute',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'one knee to chest',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'one-legged cable kickback',
    equipment: 'cable',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'physioball hip bridge',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'piriformis-smr',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'pull through',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'seated glute',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'single leg glute bridge',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'glutes (buttocks)',
    exercise: 'step-up with knee raise',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'abductors (outer thighs)',
    exercise: 'hip circles (prone)',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'abductors (outer thighs)',
    exercise: 'hip crossover',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'abductors (outer thighs)',
    exercise: 'iliotibial tract-smr',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'abductors (outer thighs)',
    exercise: 'it band and glute stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'abductors (outer thighs)',
    exercise: 'lying crossover',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'abductors (outer thighs)',
    exercise: 'monster walk',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'abductors (outer thighs)',
    exercise: 'standing hip circles',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'abductors (outer thighs)',
    exercise: 'thigh abductor',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'abductors (outer thighs)',
    exercise: 'windmills',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'adductors (inner thighs)',
    exercise: 'adductor',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'adductors (inner thighs)',
    exercise: 'adductor/groin',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'adductors (inner thighs)',
    exercise: 'adductor',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'adductors (inner thighs)',
    exercise: 'adductor/groin',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'adductors (inner thighs)',
    exercise: 'band hip adductions',
    equipment: 'bands',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'adductors (inner thighs)',
    exercise: 'carioca quick step',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'adductors (inner thighs)',
    exercise: 'groin and back stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'adductors (inner thighs)',
    exercise: 'groiners',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'adductors (inner thighs)',
    exercise: 'lateral bound',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'adductors (inner thighs)',
    exercise: 'lateral box jump',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'adductors (inner thighs)',
    exercise: 'lateral cone hops',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'adductors (inner thighs)',
    exercise: 'lying bent leg groin',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'adductors (inner thighs)',
    exercise: 'side leg raises',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'adductors (inner thighs)',
    exercise: 'side lying groin stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'legs',
    muscleSubgroup: 'adductors (inner thighs)',
    exercise: 'thigh adductor',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'ab crunch machine',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'ab roller',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'advanced kettlebell windmill',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'air bike',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'alternate heel touchers',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'ab crunch machine',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'ab roller',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'advanced kettlebell windmill',
    equipment: 'kettlebell',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'air bike',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'alternate heel touchers',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'barbell ab rollout',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'barbell ab rollout - on knees',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'barbell rollout from bench',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'barbell side bend',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'bent press',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'bent-knee hip raise',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'bosu ball cable crunch with side bends',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'bottoms up',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'butt-ups',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'cable crunch',
    equipment: 'cable',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'cable judo flip',
    equipment: 'cable',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'cable reverse crunch',
    equipment: 'cable',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'cable russian twists',
    equipment: 'cable',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'cable seated crunch',
    equipment: 'cable',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'cable tuck reverse crunch',
    equipment: 'cable',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'cocoons',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'cross-body crunch',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'crunch - hands overhead',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'crunch - legs on exercise ball',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'crunches',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'decline crunch',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'decline oblique crunch',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'decline reverse crunch',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'double kettlebell windmill',
    equipment: 'kettlebell',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'dumbbell side bend',
    equipment: 'dumbbells',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'elbow to knee',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'exercise ball crunch',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'exercise ball pull-in',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'flat bench leg pull-in',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'flat bench lying leg raise',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'frog sit-ups',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'gorilla chin/crunch',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'hanging leg raise',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'hanging pike',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'jackknife sit-up',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'janda sit-up',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'knee / hip raise on parallel bars',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'kneeling cable crunch with alternating oblique twists',
    equipment: 'cable',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'leg pull-in',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'lower back curl',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'medicine ball full twist',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'oblique crunches',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'oblique crunches - on the floor',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'one-arm high-pulley cable side bends',
    equipment: 'cable',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'one-arm medicine ball slam',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'otis-up',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'overhead stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'pallof press with rotation',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'plank',
    equipment: 'bodyweight',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'plank with twist',
    equipment: 'bodyweight',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'plate twist',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'press sit-up',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'reverse crunch',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'rope crunch',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'russian twist',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'scissor kick',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'seated barbell twist',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'seated flat bench leg pull-in',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'seated leg tucks',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'seated overhead stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'side bridge',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'side jackknife',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'sit-up',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'sledgehammer swings',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'smith machine hip raise',
    equipment: 'machine',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'spell caster',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'spider crawl',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'standing cable lift',
    equipment: 'cable',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'standing cable wood chop',
    equipment: 'cable',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'standing lateral stretch',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'standing rope crunch',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'stomach vacuum',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'supine one-arm overhead throw',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'supine two-arm overhead throw',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'suspended reverse crunch',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'toe touchers',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'torso rotation',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'tuck crunch',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'weighted ball side bend',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'weighted crunches',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'weighted sit-ups - with bands',
    equipment: 'none',
  },
  {
    muscleGroup: 'abdominals',
    muscleSubgroup: 'abdominals',
    exercise: 'wind sprints',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'aerobic exercise',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'bicycling',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'circuit training',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'elliptical trainer',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'jumping jacks',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'jump rope',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'kickboxing',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'pilates',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'rowing',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'running',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'skating',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'sprinting',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'stair climbing',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'stationary bike',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'step aerobics',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'swimming',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'treadmill',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'walking',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'water aerobics',
    equipment: 'none',
  },
  {
    muscleGroup: 'cardio',
    muscleSubgroup: 'cardio',
    exercise: 'zumba',
    equipment: 'none',
  },
];
