export const SERIES_QUERY_BASE = '/series';

export const SERIES_QUERY_KEYS = {
  GET_SERIES: 'GET_SERIES',
  CREATE_SERIES: 'CREATE_SERIES',
  UPDATE_SERIES: 'UPDATE_SERIES',
  DELETE_SERIES: 'DELETE_SERIES',
};
