export const ROUTINE_QUERIES_KEYS = {
  GET_ALL_ROUTINES: 'GET_ALL_ROUTINES',
  GET_ROUTINE: 'GET_ROUTINE',
  GET_ROUTINE_BY_ID: (id: string) => ['GET_ROUTINE_BY_ID', id],
  GET_ACTIVE_ROUTINE: 'GET_ACTIVE_ROUTINE',
} as const;
