export const STORAGE_QUERY_BASE = '/storage';

export const STORAGE_QUERY_KEYS = {
  GET_BOOK_URL: 'GET_BOOK_URL',
  PRESIGN_UPLOAD: 'PRESIGN_UPLOAD',
  UPLOAD_TO_PRESIGNED_URL: 'UPLOAD_TO_PRESIGNED_URL',
};
