export const BOOKS_QUERY_BASE = '/books';

export const BOOK_QUERIES_KEYS = {
  GET_BOOKS: 'GET_BOOKS',
  GET_BOOK_BY_ID: 'GET_BOOK_BY_ID',
  GET_BOOK_URL: 'GET_BOOK_URL',
  PRESIGN_BOOK_UPLOAD: 'PRESIGN_BOOK_UPLOAD',
  UPLOAD_TO_PRESIGNED_URL: 'UPLOAD_TO_PRESIGNED_URL',
  COMPLETE_BOOK_UPLOAD: 'COMPLETE_BOOK_UPLOAD',
  DELETE_BOOK: 'DELETE_BOOK',
  UPDATE_BOOK: 'UPDATE_BOOK',
};
